package cn.jbolt.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("change_log", "id", ChangeLog.class);
		arp.addMapping("demotable", "id", Demotable.class);
		arp.addMapping("dictionary", "id", Dictionary.class);
		arp.addMapping("dictionary_type", "id", DictionaryType.class);
		arp.addMapping("download_log", "id", DownloadLog.class);
		arp.addMapping("global_config", "id", GlobalConfig.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("goods_attr", "id", GoodsAttr.class);
		arp.addMapping("goods_back_category", "id", GoodsBackCategory.class);
		arp.addMapping("goods_element_content", "id", GoodsElementContent.class);
		arp.addMapping("goods_group", "id", GoodsGroup.class);
		arp.addMapping("goods_html_content", "id", GoodsHtmlContent.class);
		arp.addMapping("goods_type", "id", GoodsType.class);
		arp.addMapping("goods_type_brand", "id", GoodsTypeBrand.class);
		arp.addMapping("jbolt_file", "id", JboltFile.class);
		arp.addMapping("jbolt_version", "id", JboltVersion.class);
		arp.addMapping("jbolt_version_file", "id", JboltVersionFile.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("order_item", "id", OrderItem.class);
		arp.addMapping("order_shipping", "id", OrderShipping.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("rental", "id", Rental.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("role_permission", "id", RolePermission.class);
		arp.addMapping("shelf", "id", Shelf.class);
		arp.addMapping("shelf_activity", "id", ShelfActivity.class);
		arp.addMapping("shelf_carousel", "id", ShelfCarousel.class);
		arp.addMapping("shelf_element", "id", ShelfElement.class);
		arp.addMapping("shelf_goods_floor", "id", ShelfGoodsFloor.class);
		arp.addMapping("shelf_goods_group", "id", ShelfGoodsGroup.class);
		arp.addMapping("sku", "id", Sku.class);
		arp.addMapping("sku_item", "id", SkuItem.class);
		arp.addMapping("spec", "id", Spec.class);
		arp.addMapping("spec_item", "id", SpecItem.class);
		arp.addMapping("system_log", "id", SystemLog.class);
		arp.addMapping("update_libs", "id", UpdateLibs.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("wechat_article", "id", WechatArticle.class);
		arp.addMapping("wechat_autoreply", "id", WechatAutoreply.class);
		arp.addMapping("wechat_config", "id", WechatConfig.class);
		arp.addMapping("wechat_keywords", "id", WechatKeywords.class);
		arp.addMapping("wechat_menu", "id", WechatMenu.class);
		arp.addMapping("wechat_mpinfo", "id", WechatMpinfo.class);
		arp.addMapping("wechat_reply_content", "id", WechatReplyContent.class);
	}
}

