package cn.jbolt.common.model;

import java.util.List;

import cn.jbolt.common.bean.Option;
import cn.jbolt.common.model.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> implements Option{
	public static final Dictionary dao=new Dictionary().dao();

	@Override
	public Object getValue() {
		return getId();
	}

	@Override
	public String getText() {
		return getName();
	} 
	/**
	 * 获取下级子项目
	 * @return
	 */
	public List<Dictionary> getItems(){
		return this.get("items");
	}
	
	
}
