package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseDictionaryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictionaryType extends BaseDictionaryType<DictionaryType> {
	public static final DictionaryType dao = new DictionaryType().dao();
	/**
	 * 层级 一级
	 */
	public static final int MODE_LEVEL_1=1;
	/**
	 * 层级 二级
	 */
	public static final int MODE_LEVEL_2=2;
}
