package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGlobalConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GlobalConfig extends BaseGlobalConfig<GlobalConfig> {
	public static final GlobalConfig dao = new GlobalConfig().dao();
}
