package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsType extends BaseGoodsType<GoodsType> {
	public static final GoodsType dao = new GoodsType().dao();
}
