package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodsHtmlContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsHtmlContent extends BaseGoodsHtmlContent<GoodsHtmlContent> {
	public static final GoodsHtmlContent dao = new GoodsHtmlContent().dao();
}
