package cn.jbolt.common.model;

import java.util.List;

import cn.jbolt.common.model.base.BaseGoodsBackCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsBackCategory extends BaseGoodsBackCategory<GoodsBackCategory> {
	public static final GoodsBackCategory dao = new GoodsBackCategory().dao();
	
	public void putItems(List<GoodsBackCategory> items){
		put("items",items);
	}
	
	public List<GoodsBackCategory> getItems(){
		return get("items");
	}
	/**
	 * 树形结构上单独使用的
	 * @return
	 */
	public String getEnableName() {
		String name=super.getName();
		Boolean enable=getEnable();
		return (enable!=null&&enable)?name:(name+"[<span class='text-danger'>禁用</span>]");
	}
}
