package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseJboltVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JboltVersion extends BaseJboltVersion<JboltVersion> {
	public static final JboltVersion dao = new JboltVersion().dao();
}
