package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseJboltVersionFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JboltVersionFile extends BaseJboltVersionFile<JboltVersionFile> {
	public static final JboltVersionFile dao = new JboltVersionFile().dao();
}
