package cn.jbolt.common.model;

import java.util.List;

import cn.jbolt.common.bean.Option;
import cn.jbolt.common.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> implements Option {
	public static final Permission dao = new Permission().dao();
	public static final int LEVEL_1=1;
	public static final int LEVEL_2=2;
	public static final int LEVEL_3=3;
	private static final String SPRIT="/";
	
	public List<Permission> getItems() {
		return get("items");
	}
	public void putItems(List<Permission> items) {
		put("items",items);
	}
	
/*	public String getAbUrl(){
		String url=getUrl();
		if(StrKit.isBlank(url)){
			return "";
		}
		return SPRIT+url;
	}*/

	@Override
	public Object getValue() {
		return getId();
	}

	@Override
	public String getText() {
		return getTitle();
	}
}
