package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseRental;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rental extends BaseRental<Rental> {

    public final static Rental dao = new Rental();
}
