package cn.jbolt.common.model;

import cn.jbolt.common.bean.Option;
import cn.jbolt.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> implements Option{
	public static final Role dao = new Role().dao();

	@Override
	public Object getValue() {
		return getId();
	}

	@Override
	public String getText() {
		return getName();
	}
}
