package cn.jbolt.common.model;


import java.util.List;

import cn.jbolt.common.model.base.BaseUser;
import cn.jbolt.common.util.CACHE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao=new User().dao();
	public List<Role> getUserRoles(){
		return CACHE.me.getRoles(getRoles());
	}
	
	
	
	
}
