package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatAutoreply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatAutoreply extends BaseWechatAutoreply<WechatAutoreply> {
	public static final WechatAutoreply dao = new WechatAutoreply().dao();
}
