package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatReplyContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatReplyContent extends BaseWechatReplyContent<WechatReplyContent> {
	public static final WechatReplyContent dao = new WechatReplyContent().dao();
}
