package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatKeywords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatKeywords extends BaseWechatKeywords<WechatKeywords> {
	public static final WechatKeywords dao = new WechatKeywords().dao();
}
