package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatConfig extends BaseWechatConfig<WechatConfig> {
	public static final WechatConfig dao = new WechatConfig().dao();
	/**
	 * 配置类型-基础配置
	 */
	public final static int TYPE_BASE=1;
	/**
	 * 配置类型-支付配置
	 */
	public final static int TYPE_PAY=2;
}
