package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
		return (M)this;
	}
	
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setWxuserId(java.lang.Integer wxuserId) {
		set("wxuserId", wxuserId);
		return (M)this;
	}
	
	public java.lang.Integer getWxuserId() {
		return getInt("wxuserId");
	}

	public M setWxuserName(java.lang.String wxuserName) {
		set("wxuserName", wxuserName);
		return (M)this;
	}
	
	public java.lang.String getWxuserName() {
		return getStr("wxuserName");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setPaymentTime(java.util.Date paymentTime) {
		set("paymentTime", paymentTime);
		return (M)this;
	}
	
	public java.util.Date getPaymentTime() {
		return get("paymentTime");
	}

	public M setConsignTime(java.util.Date consignTime) {
		set("consignTime", consignTime);
		return (M)this;
	}
	
	public java.util.Date getConsignTime() {
		return get("consignTime");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finishTime", finishTime);
		return (M)this;
	}
	
	public java.util.Date getFinishTime() {
		return get("finishTime");
	}

	public M setCloseTime(java.util.Date closeTime) {
		set("closeTime", closeTime);
		return (M)this;
	}
	
	public java.util.Date getCloseTime() {
		return get("closeTime");
	}

	public M setBuyerMessage(java.lang.String buyerMessage) {
		set("buyerMessage", buyerMessage);
		return (M)this;
	}
	
	public java.lang.String getBuyerMessage() {
		return getStr("buyerMessage");
	}

	public M setBuyerNickname(java.lang.String buyerNickname) {
		set("buyerNickname", buyerNickname);
		return (M)this;
	}
	
	public java.lang.String getBuyerNickname() {
		return getStr("buyerNickname");
	}

	public M setBuyerRate(java.lang.Boolean buyerRate) {
		set("buyerRate", buyerRate);
		return (M)this;
	}
	
	public java.lang.Boolean getBuyerRate() {
		return get("buyerRate");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setGoodsAmount(java.math.BigDecimal goodsAmount) {
		set("goodsAmount", goodsAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getGoodsAmount() {
		return get("goodsAmount");
	}

	public M setPostFee(java.math.BigDecimal postFee) {
		set("postFee", postFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getPostFee() {
		return get("postFee");
	}

	public M setPaymentAmount(java.math.BigDecimal paymentAmount) {
		set("paymentAmount", paymentAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getPaymentAmount() {
		return get("paymentAmount");
	}

	public M setPaymentType(java.lang.Integer paymentType) {
		set("paymentType", paymentType);
		return (M)this;
	}
	
	public java.lang.Integer getPaymentType() {
		return getInt("paymentType");
	}

	public M setOnlinePaymentType(java.lang.Integer onlinePaymentType) {
		set("onlinePaymentType", onlinePaymentType);
		return (M)this;
	}
	
	public java.lang.Integer getOnlinePaymentType() {
		return getInt("onlinePaymentType");
	}

}
