package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRental<M extends BaseRental<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTaxId(java.lang.String taxId) {
		set("tax_id", taxId);
		return (M)this;
	}
	
	public java.lang.String getTaxId() {
		return getStr("tax_id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public M setRegAddress(java.lang.String regAddress) {
		set("reg_address", regAddress);
		return (M)this;
	}
	
	public java.lang.String getRegAddress() {
		return getStr("reg_address");
	}

	public M setRepresentativeName(java.lang.String representativeName) {
		set("representative_name", representativeName);
		return (M)this;
	}
	
	public java.lang.String getRepresentativeName() {
		return getStr("representative_name");
	}

	public M setRepresentativePhone(java.lang.String representativePhone) {
		set("representative_phone", representativePhone);
		return (M)this;
	}
	
	public java.lang.String getRepresentativePhone() {
		return getStr("representative_phone");
	}

	public M setAgentNamePhone(java.lang.String agentNamePhone) {
		set("agent_name_phone", agentNamePhone);
		return (M)this;
	}
	
	public java.lang.String getAgentNamePhone() {
		return getStr("agent_name_phone");
	}

	public M setFirstRentalDate(java.lang.String firstRentalDate) {
		set("first_rental_date", firstRentalDate);
		return (M)this;
	}
	
	public java.lang.String getFirstRentalDate() {
		return getStr("first_rental_date");
	}

	public M setAddressFrom(java.lang.String addressFrom) {
		set("address_from", addressFrom);
		return (M)this;
	}
	
	public java.lang.String getAddressFrom() {
		return getStr("address_from");
	}

	public M setCost(java.math.BigDecimal cost) {
		set("cost", cost);
		return (M)this;
	}
	
	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public M setCostDate(java.util.Date costDate) {
		set("cost_date", costDate);
		return (M)this;
	}
	
	public java.util.Date getCostDate() {
		return get("cost_date");
	}

	public M setHasTaxControl(java.lang.Integer hasTaxControl) {
		set("has_tax_control", hasTaxControl);
		return (M)this;
	}
	
	public java.lang.Integer getHasTaxControl() {
		return getInt("has_tax_control");
	}

	public M setCompanyAttrib(java.lang.Integer companyAttrib) {
		set("company_attrib", companyAttrib);
		return (M)this;
	}
	
	public java.lang.Integer getCompanyAttrib() {
		return getInt("company_attrib");
	}

	public M setCompanyProject(java.lang.String companyProject) {
		set("company_project", companyProject);
		return (M)this;
	}
	
	public java.lang.String getCompanyProject() {
		return getStr("company_project");
	}

	public M setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
		return (M)this;
	}
	
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public M setCreator(java.lang.Integer creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setModifyBy(java.lang.Integer modifyBy) {
		set("modify_by", modifyBy);
		return (M)this;
	}
	
	public java.lang.Integer getModifyBy() {
		return getInt("modify_by");
	}

	public M setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
		return (M)this;
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
