package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("originalPrice", originalPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getOriginalPrice() {
		return get("originalPrice");
	}

	public M setMainImage(java.lang.String mainImage) {
		set("mainImage", mainImage);
		return (M)this;
	}
	
	public java.lang.String getMainImage() {
		return getStr("mainImage");
	}

	public M setExtraImages(java.lang.String extraImages) {
		set("extraImages", extraImages);
		return (M)this;
	}
	
	public java.lang.String getExtraImages() {
		return getStr("extraImages");
	}

	public M setContentType(java.lang.Integer contentType) {
		set("contentType", contentType);
		return (M)this;
	}
	
	public java.lang.Integer getContentType() {
		return getInt("contentType");
	}

	public M setGroups(java.lang.String groups) {
		set("groups", groups);
		return (M)this;
	}
	
	public java.lang.String getGroups() {
		return getStr("groups");
	}

	public M setStockCount(java.lang.Integer stockCount) {
		set("stockCount", stockCount);
		return (M)this;
	}
	
	public java.lang.Integer getStockCount() {
		return getInt("stockCount");
	}

	public M setSubTitle(java.lang.String subTitle) {
		set("subTitle", subTitle);
		return (M)this;
	}
	
	public java.lang.String getSubTitle() {
		return getStr("subTitle");
	}

	public M setIsMultispec(java.lang.Boolean isMultispec) {
		set("isMultispec", isMultispec);
		return (M)this;
	}
	
	public java.lang.Boolean getIsMultispec() {
		return get("isMultispec");
	}

	public M setLimitCount(java.lang.Integer limitCount) {
		set("limitCount", limitCount);
		return (M)this;
	}
	
	public java.lang.Integer getLimitCount() {
		return getInt("limitCount");
	}

	public M setLocationLabel(java.lang.String locationLabel) {
		set("locationLabel", locationLabel);
		return (M)this;
	}
	
	public java.lang.String getLocationLabel() {
		return getStr("locationLabel");
	}

	public M setIsProvideInvoices(java.lang.Boolean isProvideInvoices) {
		set("isProvideInvoices", isProvideInvoices);
		return (M)this;
	}
	
	public java.lang.Boolean getIsProvideInvoices() {
		return get("isProvideInvoices");
	}

	public M setIsGuarantee(java.lang.Boolean isGuarantee) {
		set("isGuarantee", isGuarantee);
		return (M)this;
	}
	
	public java.lang.Boolean getIsGuarantee() {
		return get("isGuarantee");
	}

	public M setOnSale(java.lang.Boolean onSale) {
		set("onSale", onSale);
		return (M)this;
	}
	
	public java.lang.Boolean getOnSale() {
		return get("onSale");
	}

	public M setUnderTime(java.util.Date underTime) {
		set("underTime", underTime);
		return (M)this;
	}
	
	public java.util.Date getUnderTime() {
		return get("underTime");
	}

	public M setOnSaleUserId(java.lang.Integer onSaleUserId) {
		set("onSaleUserId", onSaleUserId);
		return (M)this;
	}
	
	public java.lang.Integer getOnSaleUserId() {
		return getInt("onSaleUserId");
	}

	public M setOnSaleTime(java.util.Date onSaleTime) {
		set("onSaleTime", onSaleTime);
		return (M)this;
	}
	
	public java.util.Date getOnSaleTime() {
		return get("onSaleTime");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("createUserId");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("updateUserId", updateUserId);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateUserId() {
		return getInt("updateUserId");
	}

	public M setGoodsUnit(java.lang.Integer goodsUnit) {
		set("goodsUnit", goodsUnit);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsUnit() {
		return getInt("goodsUnit");
	}

	public M setRealSaleCount(java.lang.Integer realSaleCount) {
		set("realSaleCount", realSaleCount);
		return (M)this;
	}
	
	public java.lang.Integer getRealSaleCount() {
		return getInt("realSaleCount");
	}

	public M setShowSaleCount(java.lang.Integer showSaleCount) {
		set("showSaleCount", showSaleCount);
		return (M)this;
	}
	
	public java.lang.Integer getShowSaleCount() {
		return getInt("showSaleCount");
	}

	public M setTypeId(java.lang.Integer typeId) {
		set("typeId", typeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("typeId");
	}

	public M setBrandId(java.lang.Integer brandId) {
		set("brandId", brandId);
		return (M)this;
	}
	
	public java.lang.Integer getBrandId() {
		return getInt("brandId");
	}

	public M setIsHot(java.lang.Boolean isHot) {
		set("isHot", isHot);
		return (M)this;
	}
	
	public java.lang.Boolean getIsHot() {
		return get("isHot");
	}

	public M setIsRecommend(java.lang.Boolean isRecommend) {
		set("isRecommend", isRecommend);
		return (M)this;
	}
	
	public java.lang.Boolean getIsRecommend() {
		return get("isRecommend");
	}

	public M setFcategoryKey(java.lang.String fcategoryKey) {
		set("fcategoryKey", fcategoryKey);
		return (M)this;
	}
	
	public java.lang.String getFcategoryKey() {
		return getStr("fcategoryKey");
	}

	public M setBcategoryKey(java.lang.String bcategoryKey) {
		set("bcategoryKey", bcategoryKey);
		return (M)this;
	}
	
	public java.lang.String getBcategoryKey() {
		return getStr("bcategoryKey");
	}

	public M setBcategoryId(java.lang.Integer bcategoryId) {
		set("bcategoryId", bcategoryId);
		return (M)this;
	}
	
	public java.lang.Integer getBcategoryId() {
		return getInt("bcategoryId");
	}

	public M setFcategoryId(java.lang.Integer fcategoryId) {
		set("fcategoryId", fcategoryId);
		return (M)this;
	}
	
	public java.lang.Integer getFcategoryId() {
		return getInt("fcategoryId");
	}

	public M setUnderUserId(java.lang.Integer underUserId) {
		set("underUserId", underUserId);
		return (M)this;
	}
	
	public java.lang.Integer getUnderUserId() {
		return getInt("underUserId");
	}

	public M setIsDelete(java.lang.Boolean isDelete) {
		set("isDelete", isDelete);
		return (M)this;
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("isDelete");
	}

	public M setGoodsNo(java.lang.String goodsNo) {
		set("goodsNo", goodsNo);
		return (M)this;
	}
	
	public java.lang.String getGoodsNo() {
		return getStr("goodsNo");
	}

}
