package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsType<M extends BaseGoodsType<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public M setSortRank(java.lang.Integer sortRank) {
		set("sortRank", sortRank);
		return (M)this;
	}
	
	public java.lang.Integer getSortRank() {
		return getInt("sortRank");
	}

	public M setIsLinkBrand(java.lang.Boolean isLinkBrand) {
		set("isLinkBrand", isLinkBrand);
		return (M)this;
	}
	
	public java.lang.Boolean getIsLinkBrand() {
		return get("isLinkBrand");
	}

	public M setIsLinkSpec(java.lang.Boolean isLinkSpec) {
		set("isLinkSpec", isLinkSpec);
		return (M)this;
	}
	
	public java.lang.Boolean getIsLinkSpec() {
		return get("isLinkSpec");
	}

}
