package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSkuItem<M extends BaseSkuItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
		return (M)this;
	}
	
	public java.lang.Integer getSkuId() {
		return getInt("skuId");
	}

	public M setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	public M setTypeId(java.lang.Integer typeId) {
		set("typeId", typeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("typeId");
	}

	public M setSpecId(java.lang.Integer specId) {
		set("specId", specId);
		return (M)this;
	}
	
	public java.lang.Integer getSpecId() {
		return getInt("specId");
	}

	public M setSpecItemId(java.lang.Integer specItemId) {
		set("specItemId", specItemId);
		return (M)this;
	}
	
	public java.lang.Integer getSpecItemId() {
		return getInt("specItemId");
	}

}
