package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDictionaryType<M extends BaseDictionaryType<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setModeLevel(java.lang.Integer modeLevel) {
		set("modeLevel", modeLevel);
		return (M)this;
	}
	
	public java.lang.Integer getModeLevel() {
		return getInt("modeLevel");
	}

	public M setTypeKey(java.lang.String typeKey) {
		set("typeKey", typeKey);
		return (M)this;
	}
	
	public java.lang.String getTypeKey() {
		return getStr("typeKey");
	}

}
