package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setIcons(java.lang.String icons) {
		set("icons", icons);
		return (M)this;
	}
	
	public java.lang.String getIcons() {
		return getStr("icons");
	}

	public M setSortRank(java.lang.Integer sortRank) {
		set("sortRank", sortRank);
		return (M)this;
	}
	
	public java.lang.Integer getSortRank() {
		return getInt("sortRank");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public M setPermissionKey(java.lang.String permissionKey) {
		set("permissionKey", permissionKey);
		return (M)this;
	}
	
	public java.lang.String getPermissionKey() {
		return getStr("permissionKey");
	}

	public M setIsMenu(java.lang.Boolean isMenu) {
		set("isMenu", isMenu);
		return (M)this;
	}
	
	public java.lang.Boolean getIsMenu() {
		return get("isMenu");
	}

	public M setIsTargetBlank(java.lang.Boolean isTargetBlank) {
		set("isTargetBlank", isTargetBlank);
		return (M)this;
	}
	
	public java.lang.Boolean getIsTargetBlank() {
		return get("isTargetBlank");
	}

}
