package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsTypeBrand<M extends BaseGoodsTypeBrand<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGoodsTypeId(java.lang.Integer goodsTypeId) {
		set("goodsTypeId", goodsTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsTypeId() {
		return getInt("goodsTypeId");
	}

	public M setBrandId(java.lang.Integer brandId) {
		set("brandId", brandId);
		return (M)this;
	}
	
	public java.lang.Integer getBrandId() {
		return getInt("brandId");
	}

}
