package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShelf<M extends BaseShelf<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
		return (M)this;
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("createUserId");
	}

	public M setPublishUserId(java.lang.Integer publishUserId) {
		set("publishUserId", publishUserId);
		return (M)this;
	}
	
	public java.lang.Integer getPublishUserId() {
		return getInt("publishUserId");
	}

	public M setPublishTime(java.util.Date publishTime) {
		set("publishTime", publishTime);
		return (M)this;
	}
	
	public java.util.Date getPublishTime() {
		return get("publishTime");
	}

	public M setShareImg(java.lang.String shareImg) {
		set("shareImg", shareImg);
		return (M)this;
	}
	
	public java.lang.String getShareImg() {
		return getStr("shareImg");
	}

	public M setSubTitle(java.lang.String subTitle) {
		set("subTitle", subTitle);
		return (M)this;
	}
	
	public java.lang.String getSubTitle() {
		return getStr("subTitle");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("updateUserId", updateUserId);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateUserId() {
		return getInt("updateUserId");
	}

}
