package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDownloadLog<M extends BaseDownloadLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
		return (M)this;
	}
	
	public java.lang.String getIpaddress() {
		return getStr("ipaddress");
	}

	public M setDownloadType(java.lang.Integer downloadType) {
		set("downloadType", downloadType);
		return (M)this;
	}
	
	public java.lang.Integer getDownloadType() {
		return getInt("downloadType");
	}

	public M setDownloadTime(java.util.Date downloadTime) {
		set("downloadTime", downloadTime);
		return (M)this;
	}
	
	public java.util.Date getDownloadTime() {
		return get("downloadTime");
	}

}
