package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUpdateLibs<M extends BaseUpdateLibs<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setTarget(java.lang.String target) {
		set("target", target);
		return (M)this;
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public M setDeleteAll(java.lang.Boolean deleteAll) {
		set("deleteAll", deleteAll);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleteAll() {
		return get("deleteAll");
	}

	public M setMust(java.lang.Boolean must) {
		set("must", must);
		return (M)this;
	}
	
	public java.lang.Boolean getMust() {
		return get("must");
	}

}
