package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatKeywords<M extends BaseWechatKeywords<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMpId(java.lang.Integer mpId) {
		set("mpId", mpId);
		return (M)this;
	}
	
	public java.lang.Integer getMpId() {
		return getInt("mpId");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setAutoReplyId(java.lang.Integer autoReplyId) {
		set("autoReplyId", autoReplyId);
		return (M)this;
	}
	
	public java.lang.Integer getAutoReplyId() {
		return getInt("autoReplyId");
	}

}
