package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShelfCarousel<M extends BaseShelfCarousel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setImgurl(java.lang.String imgurl) {
		set("imgurl", imgurl);
		return (M)this;
	}
	
	public java.lang.String getImgurl() {
		return getStr("imgurl");
	}

	public M setOpenType(java.lang.Integer openType) {
		set("openType", openType);
		return (M)this;
	}
	
	public java.lang.Integer getOpenType() {
		return getInt("openType");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setShelfId(java.lang.Integer shelfId) {
		set("shelfId", shelfId);
		return (M)this;
	}
	
	public java.lang.Integer getShelfId() {
		return getInt("shelfId");
	}

	public M setShelfElemetId(java.lang.Integer shelfElemetId) {
		set("shelfElemetId", shelfElemetId);
		return (M)this;
	}
	
	public java.lang.Integer getShelfElemetId() {
		return getInt("shelfElemetId");
	}

	public M setSortRank(java.lang.Integer sortRank) {
		set("sortRank", sortRank);
		return (M)this;
	}
	
	public java.lang.Integer getSortRank() {
		return getInt("sortRank");
	}

}
