package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDemotable<M extends BaseDemotable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDemoDate(java.util.Date demoDate) {
		set("demoDate", demoDate);
		return (M)this;
	}
	
	public java.util.Date getDemoDate() {
		return get("demoDate");
	}

	public M setDemoTime(java.util.Date demoTime) {
		set("demoTime", demoTime);
		return (M)this;
	}
	
	public java.util.Date getDemoTime() {
		return get("demoTime");
	}

	public M setDemoDateTime(java.util.Date demoDateTime) {
		set("demoDateTime", demoDateTime);
		return (M)this;
	}
	
	public java.util.Date getDemoDateTime() {
		return get("demoDateTime");
	}

	public M setDemoWeek(java.lang.String demoWeek) {
		set("demoWeek", demoWeek);
		return (M)this;
	}
	
	public java.lang.String getDemoWeek() {
		return getStr("demoWeek");
	}

	public M setDemoMonth(java.lang.String demoMonth) {
		set("demoMonth", demoMonth);
		return (M)this;
	}
	
	public java.lang.String getDemoMonth() {
		return getStr("demoMonth");
	}

}
