package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsElementContent<M extends BaseGoodsElementContent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goodsId");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setSortRank(java.lang.Integer sortRank) {
		set("sortRank", sortRank);
		return (M)this;
	}
	
	public java.lang.Integer getSortRank() {
		return getInt("sortRank");
	}

	public M setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
		return (M)this;
	}
	
	public java.lang.Integer getSkuId() {
		return getInt("skuId");
	}

}
